name: CI

on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Hotel Miranda Laravel website's CI/CD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Inicio del despliegue..."
            cd /var/www/Laravel
            git pull origin main
            ./vendor/bin/sail composer install --no-interaction --prefer-dist
            ./vendor/bin/sail artisan migrate --force
            sudo systemctl restart apache2
